version: "3"
services:

  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      #- "80:80" 
      #- "8080:8080"
      - "443:443" 
    command:
      - --api.insecure=true 
      - --api.dashboard=true 
      - --api.debug=true 
      - --log.level=DEBUG 
      - --providers.docker=true 
      - --providers.docker.exposedbydefault=false 
      - --providers.docker.network=mynet 
      - --entrypoints.web-secured.address=:443 
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true 
      - --certificatesresolvers.mytlschallenge.acme.email=theafkdeveloper@gmail.com 
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json 
      - --certificatesresolvers.mytlschallenge.acme.caserver=https://acme-v02.api.letsencrypt.org/directory   
    volumes:
      - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
     
    networks:
      - mynet 
    labels:
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.api.rule=Host(`devops-server21.ddns.net`)" 
      - "traefik.http.routers.api.service=api@internal" 
      - "traefik.http.routers.api.entrypoints=web-secured"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=mytlschallenge"


  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
   # ports:
   #   - 8080:8080
   #   - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      - JENKINS_OPTS="--prefix=/jenkins/"
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins{regex:$$|/.*}`)"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.entrypoints=web-secured"
      - "traefik.http.routers.jenkins.tls.certresolver=mytlschallenge"
      #- "traefik.http.services.jenkins.loadbalancer.server.port=8080"

      - "traefik.http.routers.jenkins_back.tls=true"
      - "traefik.http.routers.jenkins_back.entrypoints=web-secured"
      - "traefik.http.routers.jenkins_back.tls.certresolver=mytlschallenge"
      #- "traefik.http.routers.jenkins_back.service=jenkins_back"
      - "traefik.http.services.jenkins_back.loadbalancer.server.port=8080"

    networks:
      - mynet


networks:
  mynet:
    external: true
