---
- hosts: "{{ ehosts | default('local') }}"
  become: true
  roles:
  - { role: docker, tags: ["docker"] }
  - { role: elasticsearch, tags: ["elasticsearch"] }
  - { role: kibana, tags: ["kibana"] }
  - { role: logstash, tags: ["logstash"] }
  # - { role: haproxy, tags: ["haproxy"] }
