---
- name: Remove elastic search container
  docker_container:
    name: "{{ elasticsearch_hostname }}"
    state: absent
  tags:
  - elasticsearch

- name: Clean elastic search conf dir
  file:
    state: absent
    path: "{{ elasticsearch_conf_dir }}"
  tags:
  - elasticsearch

- name: Remove kibana container
  docker_container:
    name: "{{ kibana_hostname }}"
    state: absent
  tags:
  - kibana

- name: Remove logstash container
  docker_container:
    name: "{{ logstash_hostname }}"
    state: absent
  tags:
  - logstash

- name: Clean logstash conf dir
  file:
    state: absent
    path: "{{ logstash_conf_dir }}"
  tags:
  - logstash


- name: Remove heartbeat container
  docker_container:
    name: "{{ heartbeat_hostname }}"
    state: absent
  tags:
  - heartbeat

- name: Clean heartbeat conf dir
  file:
    state: absent
    path: "{{ heartbeat_conf_dir }}"
  tags:
  - heartbeat


- name: Remove traefik container
  docker_container:
    name: "{{ traefik_hostname }}"
    state: absent
  tags:
  - traefik

- name: Remove jenkins container
  docker_container:
    name: "{{ jenkins_hostname }}"
    state: absent
  tags:
  - jenkins

- name: Remove jenkins build image
  docker_image:
    name: "jenkins_built"
    state: absent
  tags:
  - jenkins_image


- name: Remove sonarqube container
  docker_image:
    name: "{{ sonar_hostname }}"
    state: absent
  tags:
  - sonarqube

- name: Remove postrgres container
  docker_image:
    name: "{{ db_hostname }}"
    state: absent
  tags:
  - postgresql

