---
- name: Remove elastic search container
  docker_container:
    name: "{{ elasticsearch_hostname }}"
    state: absent
  tags:
  - elasticsearch

- name: Clean elastic search conf dir
  file:
    state: absent
    path: "{{ elasticsearch_conf_dir }}"
  tags:
  - elasticsearch

- name: Remove kibana container
  docker_container:
    name: "{{ kibana_hostname }}"
    state: absent
  tags:
  - kibana

- name: Remove logstash container
  docker_container:
    name: "{{ logstash_hostname }}"
    state: absent
  tags:
  - logstash

- name: Clean logstash conf dir
  file:
    state: absent
    path: "{{ logstash_conf_dir }}"
  tags:
  - logstash

- name: Remove nginx container
  docker_container:
    name: "{{ nginx_hostname }}"
    state: absent
  tags:
  - nginx


#- name: Remove certbot container
#  docker_container:
#    name: "{{ certbot_hostname }}"
#    state: absent
#  tags:
#  - nginx

- name: Clean nginx conf dir
  file:
    state: absent
    path: "{{ nginx_conf_dir }}"
  tags:
  - nginx


- name: Remove heartbeat container
  docker_container:
    name: "{{ heartbeat_hostname }}"
    state: absent
  tags:
  - heartbeat

- name: Clean heartbeat conf dir
  file:
    state: absent
    path: "{{ heartbeat_conf_dir }}"
  tags:
  - heartbeat


- name: Remove haproxy container
  docker_container:
    name: "{{ haproxy_hostname }}"
    state: absent
  tags:
  - ci-cd_tools

- name: Remove jenkins container
  docker_container:
    name: "{{ jenkins_hostname }}"
    state: absent
  tags:
  - ci-cd_tools

- name: Remove jenkins build image
  docker_image:
    name: "jenkins_built"
    state: absent
  tags:
  - ci-cd_tools
