server_name: localhost
network_name: mynet

traefik_image: traefik:v2.0
traefik_hostname: traefikv2
#traefik_conf_dir: /urs/share/traefik

jenkins_hostname: jenkins

sonar_hostname: sonarqube
sonar_image: sonarqube:8.2-community

db_hostname: postgresql 
db_image: postgres

elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
elasticsearch_hostname: elasticsearch01
elasticsearch_conf_dir: /usr/share/elasticsearch

kibana_image: docker.elastic.co/kibana/kibana:7.3.2
kibana_hostname: kibana01
kibana_conf_dir: /usr/share/kibana

logstash_image: docker.elastic.co/logstash/logstash:7.4.0
logstash_hostname: logstash01
logstash_conf_dir: /usr/share/logstash

heartbeat_image: docker.elastic.co/beats/heartbeat:7.4.0
heartbeat_hostname: heartbeat01
heartbeat_servername: status.example.com
heartbeat_conf_dir: /usr/share/heartbeat/
heartbeat_urls:
- https://devops-srv01.ddns.net/
- https://devops-srv01.ddns.net/jenkins/



elastic_password: "{{ vault_elastic_password }}"
kibana_password: "{{ vault_kibana_password }}"
