- name: Start kibana container
  docker_container:
    name: "{{ kibana_hostname }}"
    image: "{{ kibana_image }}"
    env:
      servername: "{{ server_name }}"
      ELASTICSEARCH_HOSTS: "http://{{ elasticsearch_hostname }}:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "{{ elastic_password }}"

     # XPACK_MONITORING_ELASTICSEARCH_HOSTS: "http://{{ elasticsearch_hostname }}:9200"
     # XPACK_MONITORING_ENABLED: "true"
     # XPACK_MONITORING_ELASTICSEARCH_USERNAME: "elastic"
     # XPACK_MONITORING_ELASTICSEARCH_PASSWORD: "{{ elastic_password }}"
    ports:
    - 5601:5601
    volumes:
    #- "./roles/kibana/config/:/usr/share/kibana/config/"
    networks:
    - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"
