name: "status.example.com"
output.logstash:
  hosts: "logstash01:5044"
setup.kibana:
  host: "kibana01:5601"
  user: "kibana"
  password: "H6XERGxomoSvgYl21QS6"
heartbeat.monitors:
- type: http
  name: http
  urls: ["https://example.com", "https://status.example.com"]
  schedule: "@every 60s"
